version: '3.9'
services:
  mongo:
    image: "mongo"
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - "mongo-data:/data/db"
  real-estate:
    image: "real-estate"
    container_name: real-estate
    ports:
      - "3000:3000"

volumes:
  mongo-data:
